// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $AddForm from "./islands/AddForm.tsx";
import * as $Contexts_Toast from "./islands/Contexts/Toast.tsx";
import * as $CopyBtn from "./islands/CopyBtn.tsx";
import * as $FoundReference from "./islands/FoundReference.tsx";
import * as $Main from "./islands/Main.tsx";
import * as $ReferenceContent from "./islands/ReferenceContent.tsx";
import * as $SavedReference from "./islands/SavedReference.tsx";
import * as $ToggleHeight from "./islands/ToggleHeight.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AddForm.tsx": $AddForm,
    "./islands/Contexts/Toast.tsx": $Contexts_Toast,
    "./islands/CopyBtn.tsx": $CopyBtn,
    "./islands/FoundReference.tsx": $FoundReference,
    "./islands/Main.tsx": $Main,
    "./islands/ReferenceContent.tsx": $ReferenceContent,
    "./islands/SavedReference.tsx": $SavedReference,
    "./islands/ToggleHeight.tsx": $ToggleHeight,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
